name: Autobuild
on: [push, pull_request]

env:
  NeosPath: "${{ github.workspace }}/neos_install/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout NML
        uses: actions/checkout@v3
      - name: setup build environment
        uses: neos-modding-group/neos-plugin-setup-action@master
      - name: lint
        run: dotnet format --verbosity detailed --verify-no-changes ./ProjectBabble-Neos.csproj
      - name: build
        run: dotnet build ./ProjectBabble-Neos.csproj --configuration Release "-property:CopyToMods=false"
      - name: upload workflow artifacts
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' # only publish workflow artifacts for pushes to master or tags
        uses: actions/upload-artifact@v3
        with:
          name: ProjectBabbleNeos
          path: ./ProjectBabble-Neos/bin/Release/ProjectBabbleNeos.dll
          if-no-files-found: error
      - name: upload release artifacts
        if: startsWith(github.ref, 'refs/tags/') # only publish release artifacts for pushes to tags
        uses: softprops/action-gh-release@v1
        with:
          draft: true # if creating a new release, make it a draft
          files: ./ProjectBabbleNeos/bin/Release/ProjectBabbleNeos.dll
          fail_on_unmatched_files: true

